version: "3.3"
services:
  fan-control:
    build: .
    container_name: fan-control
    ports:
      - 3333:3333
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /storage/db/dell-r730xd-fan-speed.db:/app/bin/data.db:ro
    restart: unless-stopped
